Portfolio desktop version
ridwanediallo/Portfolio pull request #7
Opened 2022-01-13 20:06 UTC by ridwanediallo

# Portfolio: develop desktop version using media queries

> The template used: [Template 1](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

## PR cover these tasks:

- Create a desktop version according to the aforementioned template.
- Use media queries to implement a responsive web page that toggles between desktop and mobile
versions at the `992px` mark.
- Make sure the desktop version _looks good_ in the range `992px - 1100px`.
- Make sure the web page _looks good_ in the transition between mobile and desktop versions.
- Use both _Flexbox_ and _CSS Grid_ for the layout.
- Stick the template as much as possible.

2022-01-13 22:10 UTC, elmar8287 requested changes
Hi @ridwanediallo ,

Great work on making the project requirements 👏 

**Very nice PR description 👍 🥇** 

There are still some requirements that aren't done yet, please work on it and ask for another review.
      
 ## Required Changes ♻️

- [ ] Please, consider comments under review
- [ ] Please, fix the nav links and hamburger icon missing when the screen weight is 992

![2022-01-14 01 30 01](https://user-images.githubusercontent.com/49064106/149416797-b5627363-e555-4d01-b9dc-a9cdb38d2d8d.gif)

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-13 22:10 UTC, elmar8287 commented on index.html
> +              <p class="description">
- [ ] It will be better to fix the `h1` title to be on two lines, like Figma template design
> Figma design 
<img width="484" alt="Screen Shot 2022-01-14 at 01 51 56" src="https://user-images.githubusercontent.com/49064106/149415622-8750d58b-0c02-4224-9ba9-77a153bd5c8b.png">
.

2022-01-13 22:10 UTC, elmar8287 commented on index.html
> +      </form>
- [ ] Please, consider the submit button design (hover, pressed, disabled). You can see, after submitting the form, the button change style. 
![2022-01-14 02 01 00](https://user-images.githubusercontent.com/49064106/149416330-c8d5eb90-bd90-4c96-8f6d-aa62db023f21.gif)

2022-01-13 23:28 UTC, elmar8287 requested changes
Hi @ridwanediallo ,

Great work on making the project requirements 👏 

There are still some requirements that aren't done yet, please work on it and ask for another review.
      
 ## Required Changes ♻️

- [ ] Please, consider comments under review
- [ ] Please, consider that the switching from mobile to desktop version starts when the screen weight is 801. Please, try to set it from 992.

![2022-01-14 03 12 07](https://user-images.githubusercontent.com/49064106/149424735-e0cace0b-715e-41f4-a440-5d01e8b1b288.gif)


#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-13 23:28 UTC, elmar8287 commented on index.html
> +      </form>
- [ ] Please, consider, that you still have not fixed my mentioned issue with the "Get in touch" button. 
![2022-01-14 03 23 52](https://user-images.githubusercontent.com/49064106/149424512-de46a02c-7661-4415-ba15-a10e10b6094f.gif)

2022-01-14 07:30 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @ridwanediallo ,  

Your project is complete! Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

- [ ] You still have underline text in buttons, please make sure to delete the underlie to fully comply with the requirements. You can simply do it by setting: 
`button{ text-decoration: none;}`

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 07:55 UTC, ridwanediallo commented
Hi @ShoiraTa,
Thank you for the review 👍.

2022-01-14 09:14 UTC, merged